
version: "3"

services:
 reverse-proxy:
  image: nginx:1.17.10
  container_name: reverse_proxy_demo
  depends_on:
   - esb
   - cliente
   - repartidor
   - restaurante
  volumes:
   - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
  ports:
   - 80:80
   
 esb:
  container_name: servicioesb
  restart: always
  build: ./src/ESB
  ports:
   - "3333:3333"


 cliente:
  container_name: serviciocliente
  restart: always
  build: ./src/Cliente
  ports:
   - "4000:4000"

 repartidor:
  container_name: serviciorepartidor
  restart: always
  build: ./src/Repartidor
  ports:
   - "3000:3000"

 restaurante:
  container_name: serviciorest
  restart: always
  build: ./src/Restaurante
  ports:
   - "8000:8000"
